// <auto-generated />
using System;
using AspNetCore.GraphQL.Api.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCore.GraphQL.Api.Migrations
{
    [DbContext(typeof(GraphQlContext))]
    partial class GraphQlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCore.GraphQL.Api.Models.Entity.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Number");

                    b.HasKey("Id");

                    b.ToTable("Department","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Building 1, First Floor, Door 10",
                            Number = 101
                        },
                        new
                        {
                            Id = 2,
                            Location = "Building 1, First Floor, Door 11",
                            Number = 102
                        },
                        new
                        {
                            Id = 3,
                            Location = "Building 1, First Floor, Door 12",
                            Number = 103
                        });
                });

            modelBuilder.Entity("AspNetCore.GraphQL.Api.Models.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("HireDate");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Jan",
                            HireDate = new DateTime(2019, 9, 9, 11, 7, 22, 385, DateTimeKind.Local).AddTicks(4782),
                            JobTitle = "Prof.",
                            LastName = "Sauer"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FirstName = "Jack",
                            HireDate = new DateTime(2019, 9, 9, 11, 7, 22, 387, DateTimeKind.Local).AddTicks(1506),
                            JobTitle = "Prof.",
                            LastName = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            FirstName = "Henry",
                            HireDate = new DateTime(2019, 9, 9, 11, 7, 22, 387, DateTimeKind.Local).AddTicks(1525),
                            JobTitle = "Ass.",
                            LastName = "Duncan"
                        });
                });

            modelBuilder.Entity("AspNetCore.GraphQL.Api.Models.Entity.Employee", b =>
                {
                    b.HasOne("AspNetCore.GraphQL.Api.Models.Entity.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
